.\" 	-*- Mode: Nroff -*-
.TH "clc-lisp" "1" "Janurary 31, 2010"
.AT 1
.SH NAME
clc-clbuild \- invoke lisp with clbuild active
.SH SYNOPSIS
.B clc-lisp

.SH DESCRIPTION
This is a thin wrapper round
.I clbuild
for use with 
.I common lisp controller. 
In effect it will just run

.B clbuild lisp

.B this is not working at the moment due to a patch we need to have in clbuild

.SH BUGS

Bug reports should be sent to the debian BTS, preferably with
reportbug.

.SH SEE ALSO

.SH AUTHOR
Peter Van Eynde (pvaneynd@debian.org)

.PP
