.\" 	-*- Mode: Nroff -*-
.TH "register-common-lisp-implementation" "8" "June 5, 2002"
.AT 3
.SH NAME
(un)register-common-lisp-{implementation|source) \- internal clc commands
.SH SYNOPSIS
.B register-common-lisp-implementation 
.I implementation

.B unregister-common-lisp-implementation 
.I implementation

.B register-common-lisp-source 
.I source-package

.B unregister-common-lisp-source 
.I source-package

.B clc-update-customized-images
.I source-package

.SH DESCRIPTION
These are internal 
.I common lisp controller
commands. Common lisp source and implementation packages
use them to register themselves to the
.I common lisp controller
or to cause regeneration of implementation images if they were
selected to be present in such.

.SH BUGS

Bug reports should be sent to the debian BTS, preferably with
reportbug.

.SH SEE ALSO
.TP
The Common Lisp in Debian Manual at
.B http://cl-debian.alioth.debian.org/clid/clid.html/

.SH AUTHOR
Peter Van Eynde (pvaneynd@debian.org), Kevin M. Rosenberg
(kmr@debian.org) and Ren\('e van Bevern (rvb@progn.org) 2001-2006

.PP
