#!/bin/bash

set -e 

if [ "$EUID" != 0 ] ; then
  echo You need to be root to run this or use
  echo sudo "$@"
  exit 1
fi

if [ $1 == "setup" ] ; then
  [ -d "/usr/share/common-lisp/cl-build" ] || mkdir /usr/share/common-lisp/cl-build
  chown cl-builder:cl-builder /usr/share/common-lisp/cl-build
  (cd /usr/share/common-lisp/cl-build ; 
      echo downloading clbuild using darcs
      su --shell="/bin/sh" --command="darcs get http://common-lisp.net/project/clbuild/clbuild"
      chmod u+x clbuild )
  echo
  echo done
  exit 0
fi

if [ ! -d "/usr/share/common-lisp/cl-build" ]  ; then
  echo please first run "$0 setup" to install clbuild
  exit 2
fi
 
(/usr/share/common-lisp/cl-build 
 shift
 su --shell="/bin/sh" -- ./clbuild  "$@")
