#!/bin/sh

# Copyright (C) 2000,2004  Peter Van Eynde and Kevin M. Rosenberg
# Licensed under the LLGPL, see debian/copyright file

set -e

HOME=/tmp/
LANG=C
LC_ALL=C
export HOME LANG LC_ALL

if [ -x /usr/lib/common-lisp/bin/${1}.sh ] ; then
  sh /usr/lib/common-lisp/bin/${1}.sh install-clc
else
  echo "I cannot find the implementation script for $1 at /usr/lib/common-lisp/bin/${1}.sh"
  exit 2
fi

exit 0
