#!/bin/sh

# Copyright (C) 2000,2004  Peter Van Eynde and Kevin M. Rosenberg
# Licensed under the LLGPL, see debian/copyright file

# just nuke all caches of this library

library="$1"

echo "$library" | grep -q '[^a-zA-Z0-9-]' && echo "Found special characters in $1!" && exit 42

echo "$library" | grep -q '\.\.' && echo "Found .. in $1!" && exit 1

echo "$library" | grep -q '\/\/' && echo "Found // in $1!" && exit 2

rm -rf /var/cache/common-lisp-controller/*/*/"$1"

