#!/bin/sh

# Copyright (C) 2000,2004  Peter Van Eynde and Kevin M. Rosenberg
# Licensed under the LLGPL, see debian/copyright file

# just nuke all caches of this implementation

HOME=/tmp/
LANG=C
LC_ALL=C
export HOME LANG LC_ALL

implementation="$1"

echo "$implementation" | grep -q '[^a-zA-Z0-9-]' && echo "Found special characters in $1!" && exit 42 
echo "$implementation" | grep -q '\.\.' && echo "Found .. in $1!" && exit 1

echo "$implementation" | grep -q '\/\/' && echo "Found // in $1!" && exit 2

rm -rf /var/cache/common-lisp-controller/*/"$1"

