#!/bin/sh

set -e

# Source debconf library.
. /usr/share/debconf/confmodule

# site names
db_input medium common-lisp-controller/short-site-name || true
db_go

db_input medium common-lisp-controller/long-site-name || true
db_go
